version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///cvss.db
      - SECRET_KEY=dev-secret-key
      - JWT_SECRET_KEY=dev-jwt-secret
    volumes:
      - ./backend:/app
      - backend_data:/app/instance
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

  # Optional: PostgreSQL for production-like environment
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=cvss_db
      - POSTGRES_USER=cvss_user
      - POSTGRES_PASSWORD=cvss_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - production

volumes:
  backend_data:
  postgres_data:

